language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all --check
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
