[package]
name = "railroad_dsl"
version = "0.1.0"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
license = "MIT"
description = "A small DSL to generate syntax-diagrams"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
structopt = "0.2.12"

[dependencies.railroad]
git = "https://github.com/lukaslueg/railroad"
